/**
 * Integration test for GenresSyncService against a real Postgres.
 *
 * The HTTP boundary (TmdbClient) is mocked so CI doesn't depend on TMDB
 * being reachable, but the upsert path — TypeORM, Postgres, the actual
 * `INSERT ... ON CONFLICT (tmdb_id) DO UPDATE` — runs against the real
 * database in a testcontainer.
 *
 * What this catches that unit tests don't:
 * - The SQL generated by createQueryBuilder().orUpdate() is valid Postgres.
 * - The UNIQUE constraint on tmdb_id actually exists and fires.
 * - Re-running sync updates existing rows instead of erroring or duplicating.
 */
import { Repository } from 'typeorm';
import { Genre } from '../../src/genres/genre.entity';
import { GenresSyncService } from '../../src/genres/genres.sync';
import { TmdbClient } from '../../src/tmdb/tmdb.client';
import { TmdbGenresResponse } from '../../src/tmdb/tmdb.types';
import {
  startPostgres,
  PostgresTestContext,
} from '../utils/postgres-container';

describe('GenresSyncService (integration)', () => {
  let ctx: PostgresTestContext;
  let repo: Repository<Genre>;
  let tmdb: { fetchGenres: jest.Mock<Promise<TmdbGenresResponse>> };
  let sync: GenresSyncService;

  beforeAll(async () => {
    ctx = await startPostgres();
    repo = ctx.dataSource.getRepository(Genre);
  });

  afterAll(async () => {
    await ctx?.stop();
  });

  beforeEach(async () => {
    await ctx.dataSource.query('TRUNCATE TABLE genres CASCADE');
    tmdb = { fetchGenres: jest.fn() };
    sync = new GenresSyncService(tmdb as unknown as TmdbClient, repo);
  });

  it('inserts new rows on a clean DB', async () => {
    tmdb.fetchGenres.mockResolvedValue({
      genres: [
        { id: 28, name: 'Action' },
        { id: 18, name: 'Drama' },
      ],
    });

    const count = await sync.sync();

    expect(count).toBe(2);
    const rows = await repo.find({ order: { tmdbId: 'ASC' } });
    expect(rows).toHaveLength(2);
    expect(rows[0]).toMatchObject({ tmdbId: 18, name: 'Drama' });
    expect(rows[1]).toMatchObject({ tmdbId: 28, name: 'Action' });
  });

  it('is idempotent: running sync twice with the same payload leaves the same rows', async () => {
    const payload: TmdbGenresResponse = {
      genres: [
        { id: 28, name: 'Action' },
        { id: 18, name: 'Drama' },
      ],
    };
    tmdb.fetchGenres.mockResolvedValue(payload);

    await sync.sync();
    await sync.sync();

    const rows = await repo.find();
    expect(rows).toHaveLength(2);
  });

  it('updates the name when TMDB renames a genre (ON CONFLICT DO UPDATE path)', async () => {
    tmdb.fetchGenres.mockResolvedValueOnce({
      genres: [{ id: 28, name: 'Action' }],
    });
    await sync.sync();

    tmdb.fetchGenres.mockResolvedValueOnce({
      genres: [{ id: 28, name: 'Action & Adventure' }],
    });
    await sync.sync();

    const rows = await repo.find();
    expect(rows).toHaveLength(1);
    expect(rows[0].name).toBe('Action & Adventure');
  });

  it('skips upsert and returns 0 on an empty TMDB response', async () => {
    tmdb.fetchGenres.mockResolvedValue({ genres: [] });

    const count = await sync.sync();

    expect(count).toBe(0);
    expect(await repo.count()).toBe(0);
  });
});
